--------------------------------- MODULE cea_simple ---------------------------------
EXTENDS Sequences, Naturals, Integers, FiniteSets, TLC

\* The set of all possible document ids and document field keys.
CONSTANT Document, Key

\* Sentinel for the absence of a value.
CONSTANT Nil

\* Sentinel for an exhausted cursor.
CONSTANT EOF

\* Maximum number of actions on source cluster.
CONSTANT MaxSourceChanges




\* oplog: sequence of <<type, docId, key, value, seqno>> tuples.
VARIABLE oplog

\* Source collection: Document -> DocumentVal | Nil.
VARIABLE remoteColl

\* pseudoInsertOplog: Sequence of pseudo Insert oplog events generated by ScanComplete
VARIABLE pseudoInsertOplog

\* Ordered sequence of document ids used by the cursor during the clone phase.
VARIABLE remoteCollSeq

\* Current cursor position (positive integer or EOF).
VARIABLE cursor

\* Global monotonically increasing sequence number counter.
\* Incremented each time a new oplog entry is created.
VARIABLE seqno

vars == <<oplog, remoteColl, remoteCollSeq, cursor, seqno, pseudoInsertOplog>>

----

Range(f)     == {f[i] : i \in DOMAIN f}
Injective(f) == \A x, y \in DOMAIN f : f[x] = f[y] => x = y

DeleteElement(seq, index) ==
    [i \in 1..(Len(seq) - 1) |-> IF i < index THEN seq[i] ELSE seq[i + 1]]

ScanComplete == cursor = EOF

\* The set of all possible document field maps.
DocumentVal == [Key -> {0, Nil}]

----
\* Source collection mutations
----

Insert(d, dv) ==
    /\ remoteColl[d] = Nil
    /\ seqno'         = seqno + 1
    /\ remoteColl'    = [remoteColl EXCEPT ![d] = dv]
    /\ remoteCollSeq' = Append(remoteCollSeq, d)
    /\ oplog'         = Append(oplog, <<"i", d, Nil, dv, seqno + 1>>)
    /\ UNCHANGED <<cursor, pseudoInsertOplog>>

Init ==
    (/\ oplog             = <<>>
     /\ pseudoInsertOplog = <<>>
     /\ seqno             = 0) 
    /\ (\E c \in [Document -> DocumentVal] :
        /\ remoteColl = c
        /\ LET docs == {d \in DOMAIN c : c[d] # Nil} IN
           /\ remoteCollSeq \in [1..Cardinality(docs) -> docs]
           /\ Injective(remoteCollSeq)
    /\ cursor = 1)


Next ==
    \/ \E d \in Document : \E dv \in DocumentVal : Insert(d, dv)


==============================================================================================
