--------------------------------- MODULE cea_simple ---------------------------------
EXTENDS Sequences, Naturals, Integers, FiniteSets, TLC

\* The set of all possible document ids and document field keys.
CONSTANT Document, Key

\* Sentinel for the absence of a value.
CONSTANT Nil

\* Sentinel for an exhausted cursor.
CONSTANT EOF

\* Maximum number of actions on source cluster.
CONSTANT MaxSourceChanges




\* oplog: sequence of <<type, docId, key, value, seqno>> tuples.
VARIABLE oplog

\* Source collection: Document -> DocumentVal | Nil.
VARIABLE remoteColl

\* pseudoInsertOplog: Sequence of pseudo Insert oplog events generated by ScanComplete
VARIABLE pseudoInsertOplog

\* Ordered sequence of document ids used by the cursor during the clone phase.
VARIABLE remoteCollSeq

\* Current cursor position (positive integer or EOF).
VARIABLE cursor

\* Destination collection: Document -> DocumentVal | Nil.
VARIABLE localColl

\* Global monotonically increasing sequence number counter.
\* Incremented each time a new oplog entry is created.
VARIABLE seqno

\* LastWriteStates: per-document record of the most recently applied event.
\*   lws[d] = Nil
\*       No event has been applied for document d yet.
\*   lws[d] = [lastOpTs |-> n, lastOpWasRefetch |-> b]
\*       The last applied event for d had sequence number n.
\*       b is TRUE if that application was a re-fetch of the current source image.
VARIABLE lws

vars == <<oplog, remoteColl, remoteCollSeq, cursor, localColl, seqno, lws, pseudoInsertOplog>>

----

Range(f)     == {f[i] : i \in DOMAIN f}
Injective(f) == \A x, y \in DOMAIN f : f[x] = f[y] => x = y

DeleteElement(seq, index) ==
    [i \in 1..(Len(seq) - 1) |-> IF i < index THEN seq[i] ELSE seq[i + 1]]

ScanComplete == cursor = EOF

\* The set of all possible document field maps.
DocumentVal == [Key -> {0, Nil}]

----
\* Source collection mutations
----

Insert(d, dv) ==
    /\ remoteColl[d] = Nil
    /\ seqno'         = seqno + 1
    /\ remoteColl'    = [remoteColl EXCEPT ![d] = dv]
    /\ remoteCollSeq' = Append(remoteCollSeq, d)
    /\ oplog'         = Append(oplog, <<"i", d, Nil, dv, seqno + 1>>)
    /\ UNCHANGED <<localColl, cursor, lws, pseudoInsertOplog>>

Update(d, k) ==
    /\ remoteColl[d] # Nil
    /\ LET newVer == IF remoteColl[d][k] = Nil THEN 0 ELSE remoteColl[d][k] + 1 IN
        /\ seqno'      = seqno + 1
        /\ remoteColl' = [remoteColl EXCEPT ![d][k] = newVer]
        /\ oplog'      = Append(oplog, <<"u", d, k, newVer, seqno + 1>>)
    /\ UNCHANGED <<remoteCollSeq, cursor, localColl, lws, pseudoInsertOplog>>

Init ==
    /\ oplog             = <<>>
	/\ pseudoInsertOplog = <<>>
    /\ seqno             = 0
    /\ localColl = [d \in Document |-> Nil]
    /\ lws       = [d \in Document |-> Nil]
    /\ \E c \in [Document -> DocumentVal] :
        /\ remoteColl = c
        /\ LET docs == {d \in DOMAIN c : c[d] # Nil} IN
           /\ remoteCollSeq \in [1..Cardinality(docs) -> docs]
           /\ Injective(remoteCollSeq)
    /\ cursor = 1


Next ==
    \/ \E d \in Document : \E dv \in DocumentVal : Insert(d, dv)


==============================================================================================
